"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VotesResource = exports.VotersResource = exports.TransactionsResource = exports.SignaturesResource = exports.PeersResource = exports.NodeResource = exports.DelegatesResource = exports.DappsResource = exports.BlocksResource = exports.AccountsResource = void 0;
var accounts_1 = require("./accounts");
Object.defineProperty(exports, "AccountsResource", { enumerable: true, get: function () { return accounts_1.AccountsResource; } });
var blocks_1 = require("./blocks");
Object.defineProperty(exports, "BlocksResource", { enumerable: true, get: function () { return blocks_1.BlocksResource; } });
var dapps_1 = require("./dapps");
Object.defineProperty(exports, "DappsResource", { enumerable: true, get: function () { return dapps_1.DappsResource; } });
var delegates_1 = require("./delegates");
Object.defineProperty(exports, "DelegatesResource", { enumerable: true, get: function () { return delegates_1.DelegatesResource; } });
var node_1 = require("./node");
Object.defineProperty(exports, "NodeResource", { enumerable: true, get: function () { return node_1.NodeResource; } });
var peers_1 = require("./peers");
Object.defineProperty(exports, "PeersResource", { enumerable: true, get: function () { return peers_1.PeersResource; } });
var signatures_1 = require("./signatures");
Object.defineProperty(exports, "SignaturesResource", { enumerable: true, get: function () { return signatures_1.SignaturesResource; } });
var transactions_1 = require("./transactions");
Object.defineProperty(exports, "TransactionsResource", { enumerable: true, get: function () { return transactions_1.TransactionsResource; } });
var voters_1 = require("./voters");
Object.defineProperty(exports, "VotersResource", { enumerable: true, get: function () { return voters_1.VotersResource; } });
var votes_1 = require("./votes");
Object.defineProperty(exports, "VotesResource", { enumerable: true, get: function () { return votes_1.VotesResource; } });
//# sourceMappingURL=index.js.map